// UI copy. German is the club's home language; English is the fallback.
// Values are strings with {placeholders} or functions for plurals.

const plural = (n, one, many) => (n === 1 ? one : many).replace('{n}', n);

export const de = {
  'app.tagline': 'Euer Buchclub. Ein Rad. Jeden Monat ein neues Buch.',
  'app.loading': 'Einen Moment …',
  'common.cancel': 'Abbrechen',
  'common.save': 'Speichern',
  'common.close': 'Schließen',
  'common.delete': 'Löschen',
  'common.edit': 'Bearbeiten',
  'common.undo': 'Rückgängig',
  'common.optional': 'optional',
  'common.you': 'du',
  'common.error': 'Das hat nicht geklappt — bitte versuch es noch einmal.',
  'common.and': 'und',

  'auth.welcome': 'Willkommen im Club',
  'auth.intro': 'Stellt Bücher ins Regal, dreht am Rad und lest gemeinsam — mit Lesezielen, Fortschritt und Sterne-Bewertungen.',
  'auth.google': 'Mit Google anmelden',
  'auth.or': 'oder mit E-Mail',
  'auth.email': 'E-Mail',
  'auth.password': 'Passwort',
  'auth.name': 'Dein Name',
  'auth.signIn': 'Anmelden',
  'auth.register': 'Konto erstellen',
  'auth.toSignIn': 'Schon dabei? Anmelden',
  'auth.toRegister': 'Neu hier? Konto erstellen',
  'auth.forgot': 'Passwort vergessen?',
  'auth.resetSent': 'Falls es ein Konto gibt, ist ein Link zum Zurücksetzen unterwegs.',
  'auth.needEmail': 'Trag zuerst deine E-Mail-Adresse ein.',
  'auth.err.credentials': 'E-Mail oder Passwort stimmt nicht.',
  'auth.err.emailInUse': 'Für diese E-Mail gibt es schon ein Konto — melde dich einfach an.',
  'auth.err.weakPassword': 'Das Passwort braucht mindestens 6 Zeichen.',
  'auth.err.invalidEmail': 'Das sieht nicht nach einer gültigen E-Mail-Adresse aus.',
  'auth.err.popup': 'Das Anmeldefenster wurde geschlossen oder blockiert.',
  'auth.err.domain': 'Diese Adresse ist in Firebase noch nicht freigegeben (Authentication → Settings → Authorized domains).',
  'auth.err.disabled': 'Diese Anmeldeart ist in Firebase noch nicht aktiviert (Authentication → Sign-in method).',
  'auth.err.network': 'Keine Verbindung. Bist du online?',
  'auth.err.tooMany': 'Zu viele Versuche — warte kurz und probier es dann nochmal.',

  'demo.title': 'Demo-Modus',
  'demo.intro': 'Firebase ist noch nicht verbunden. Du kannst Bookwheel trotzdem ausprobieren — mit einem Beispiel-Club, gespeichert nur in diesem Browser.',
  'demo.start': 'Demo starten',
  'demo.banner': 'Demo-Modus · alles bleibt in diesem Browser',
  'demo.reset': 'Demo zurücksetzen',
  'demo.setup': 'Einrichtung',

  'club.createTitle': 'Gründet euren Buchclub',
  'club.createIntro': 'Hier gibt es noch keinen Club. Du wirst Gründer:in und bekommst einen Einladungscode für die anderen.',
  'club.name': 'Name des Clubs',
  'club.namePlaceholder': 'z. B. Die Seitenspringer',
  'club.create': 'Club gründen',
  'club.joinTitle': '{club} beitreten',
  'club.joinIntro': 'Gib den Einladungscode ein, den du aus dem Club bekommen hast.',
  'club.code': 'Einladungscode',
  'club.join': 'Beitreten',
  'club.badCode': 'Dieser Code passt nicht. Frag am besten nochmal im Club nach.',
  'club.signedInAs': 'Angemeldet als {who}',
  'club.switchAccount': 'Anderes Konto verwenden',

  'nav.wheel': 'Rad',
  'nav.current': 'Aktuell',
  'nav.shelf': 'Regal',
  'nav.chronicle': 'Chronik',
  'menu.profile': 'Profil',
  'menu.club': 'Club & Einladung',
  'menu.signOut': 'Abmelden',
  'menu.language': 'Sprache',
  'menu.theme': 'Design',
  'menu.sound': 'Rad-Geräusche',
  'menu.on': 'an',
  'menu.off': 'aus',
  'theme.system': 'Auto',
  'theme.light': 'Hell',
  'theme.dark': 'Dunkel',

  'hero.morning': 'Guten Morgen, {name}',
  'hero.day': 'Hallo, {name}',
  'hero.evening': 'Guten Abend, {name}',
  'hero.title': 'Was lesen wir als Nächstes?',
  'hero.titleReading': 'Gemeinsam lesen, gemeinsam drehen.',

  'wheel.title': 'Das Rad',
  'wheel.count': ({ n }) => plural(n, '{n} Buch im Rad', '{n} Bücher im Rad'),
  'wheel.filter': 'Nach Genre filtern',
  'wheel.allGenres': 'Alle Genres',
  'wheel.spin': 'Drehen!',
  'wheel.spinning': 'Das Rad dreht sich …',
  'wheel.empty': 'Das Regal ist leer — stellt ein paar Bücher hinein.',
  'wheel.emptyFilter': 'In diesen Genres steht gerade nichts im Regal.',
  'wheel.emptyCenter': 'Regal füllen',
  'wheel.confirmReplace': 'Gerade lest ihr „{title}“. Trotzdem ein neues Buch drehen?',
  'wheel.confirmYes': 'Ja, drehen',
  'wheel.taken': '„{title}“ wurde gerade schon gezogen.',

  'result.eyebrow': 'Das Rad hat entschieden',
  'result.byOther': '{name} hat am Rad gedreht!',
  'result.month': 'Buch für',
  'result.start': 'Los geht’s!',
  'result.undo': 'Zurück ins Regal',
  'result.undone': '„{title}“ steht wieder im Regal.',
  'result.pages': '{n} Seiten',

  'current.eyebrow': 'Aktuelles Buch',
  'current.none': 'Noch kein aktuelles Buch',
  'current.noneHint': 'Dreht am Rad — das gezogene Buch landet hier und alle lesen mit.',
  'current.pickedBy': 'gezogen von {name}',
  'current.forMonth': 'Buch für {month}',
  'current.pages': '{n} Seiten',
  'current.myProgress': 'Mein Fortschritt',
  'current.page': 'Seite',
  'current.ofPages': 'von {n}',
  'current.update': 'Speichern',
  'current.saved': 'Fortschritt gespeichert — Seite {page}',
  'current.markRead': 'Als gelesen markieren',
  'current.finished': 'Gelesen',
  'current.rateNow': 'Jetzt bewerten',
  'current.editRating': 'Bewertung ändern',
  'current.yourRating': 'Deine Bewertung',
  'current.notFinished': 'Doch noch nicht fertig',
  'current.pageCountMissing': 'Wie viele Seiten hat das Buch?',
  'current.setPages': 'Übernehmen',

  'goals.title': 'Leseziele',
  'goals.empty': 'Noch keine Leseziele. Legt fest, bis wann alle wie weit sein sollen.',
  'goals.item': 'Bis {date} · Seite {page}',
  'goals.add': 'Ziel hinzufügen',
  'goals.date': 'Bis zum',
  'goals.page': 'Seite',
  'goals.today': 'heute',
  'goals.tomorrow': 'morgen',
  'goals.inDays': ({ n }) => plural(n, 'in {n} Tag', 'in {n} Tagen'),
  'goals.past': 'vorbei',
  'goals.reached': ({ n, m }) => `${n} von ${m} geschafft`,
  'goals.next': 'Nächstes Ziel',
  'goals.remove': 'Ziel entfernen',
  'goals.added': 'Leseziel gespeichert',
  'goals.invalid': 'Bitte Datum und Seite angeben.',

  'ticker.title': 'Wer liest wie weit?',
  'ticker.page': 'S. {page}',
  'ticker.ofPages': 'S. {page} / {total}',
  'ticker.notStarted': 'noch nicht angefangen',
  'ticker.finished': 'fertig!',
  'ticker.behind': ({ n }) => `${n} S. hinter dem Ziel`,
  'ticker.reached': 'Ziel erreicht',
  'ticker.toGo': ({ n }) => `noch ${n} S. bis zum Ziel`,
  'ticker.empty': 'Sobald ein Buch gezogen ist, seht ihr hier, wie weit alle sind.',

  'shelf.title': 'Das Regal',
  'shelf.sub': 'Alles, was hier steht, dreht sich im Rad mit.',
  'shelf.add': 'Buch hinzufügen',
  'shelf.search': 'Im Regal suchen …',
  'shelf.empty': 'Das Regal ist noch leer. Stellt das erste Buch hinein!',
  'shelf.noMatch': 'Nichts gefunden.',
  'shelf.addedBy': 'von {name}',
  'shelf.removed': '„{title}“ aus dem Regal genommen',
  'shelf.added': '„{title}“ steht jetzt im Regal!',
  'shelf.count': ({ n }) => plural(n, '{n} Buch', '{n} Bücher'),

  'add.title': 'Neues Buch fürs Regal',
  'add.lookup': 'Buch suchen',
  'add.lookupPlaceholder': 'Titel oder Autor:in eintippen …',
  'add.lookupHint': 'Wir suchen Cover und Seitenzahl automatisch — oder trag alles selbst ein.',
  'add.searching': 'Suche …',
  'add.noResults': 'Keine Treffer — trag das Buch einfach selbst ein.',
  'add.bookTitle': 'Titel',
  'add.author': 'Autor:in',
  'add.genre': 'Genre',
  'add.pages': 'Seiten',
  'add.cover': 'Buchcover',
  'add.coverUrl': 'Bild-URL einfügen',
  'add.upload': 'Bild hochladen',
  'add.removeCover': 'Cover entfernen',
  'add.submit': 'Ins Regal stellen',
  'add.needGenre': 'Bitte wähle ein Genre.',
  'add.needTitle': 'Titel und Autor:in brauchen wir.',
  'add.coverError': 'Das Bild konnte nicht gelesen werden.',
  'add.badUrl': 'Das ist keine gültige Bild-Adresse (https://…).',
  'add.duplicate': '„{title}“ steht schon im Regal.',

  'edit.title': 'Buch bearbeiten',
  'edit.remove': 'Aus dem Regal nehmen',
  'edit.saved': 'Gespeichert',

  'review.title': 'Wie fandest du „{title}“?',
  'review.congrats': 'Geschafft! Glückwunsch zum Auslesen.',
  'review.text': 'Deine Rezension',
  'review.placeholder': 'Was hat dich begeistert, was eher nicht?',
  'review.submit': 'Bewertung abgeben',
  'review.later': 'Später bewerten',
  'review.saved': 'Danke für deine Bewertung!',
  'review.needStars': 'Wähle 1 bis 5 Sterne.',
  'review.sealed': 'Die Bewertungen bleiben verdeckt, bis alle abgestimmt haben — dann gibt’s den Durchschnitt.',
  'review.star': ({ n }) => plural(n, '{n} Stern', '{n} Sterne'),

  'chron.title': 'Chronik',
  'chron.sub': 'Jeder Monat, jedes Buch — und was ihr davon hieltet.',
  'chron.empty': 'Hier erscheinen eure gezogenen Bücher, Monat für Monat.',
  'chron.current': 'Lesen wir gerade',
  'chron.avg': 'Ø {value} von 5',
  'chron.votes': ({ n, m }) => `${n} von ${m} Bewertungen`,
  'chron.waitingFor': 'Es fehlt noch: {names}',
  'chron.showReviews': 'Rezensionen lesen',
  'chron.hideReviews': 'Rezensionen ausblenden',
  'chron.sealed': 'Die Rezensionen werden enthüllt, sobald alle bewertet haben.',
  'chron.noText': 'ohne Worte, nur Sterne',
  'chron.rate': 'Gelesen & bewerten',
  'chron.editRating': 'Meine Bewertung ändern',
  'chron.setCurrent': 'Als aktuelles Buch setzen',
  'chron.moveMonth': 'Monat ändern',
  'chron.backToShelf': 'Zurück ins Regal',
  'chron.finishedCount': ({ n }) => plural(n, '{n} hat es gelesen', '{n} haben es gelesen'),
  'chron.pickedBy': 'gezogen von {name}',

  'clubm.title': 'Club & Einladung',
  'clubm.invite': 'Einladungscode',
  'clubm.inviteHint': 'Schick neuen Mitgliedern den Link — oder den Code, den sie nach der Anmeldung eingeben.',
  'clubm.copyCode': 'Code kopieren',
  'clubm.copyLink': 'Link kopieren',
  'clubm.copied': 'Kopiert!',
  'clubm.newCode': 'Neuen Code erzeugen',
  'clubm.newCodeDone': 'Neuer Code ist aktiv. Der alte gilt nicht mehr.',
  'clubm.members': 'Mitglieder',
  'clubm.founder': 'Gründer:in',
  'clubm.remove': 'Entfernen',
  'clubm.removeConfirm': '{name} wirklich aus dem Club entfernen?',
  'clubm.leave': 'Club verlassen',
  'clubm.leaveConfirm': 'Willst du den Club wirklich verlassen?',
  'clubm.rename': 'Club umbenennen',

  'profile.title': 'Dein Profil',
  'profile.name': 'Anzeigename',
  'profile.color': 'Deine Farbe',
  'profile.saved': 'Profil gespeichert',
};

export const en = {
  'app.tagline': 'Your book club. One wheel. A new book every month.',
  'app.loading': 'One moment…',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.undo': 'Undo',
  'common.optional': 'optional',
  'common.you': 'you',
  'common.error': 'That didn’t work — please try again.',
  'common.and': 'and',

  'auth.welcome': 'Welcome to the club',
  'auth.intro': 'Put books on the shelf, spin the wheel and read together — with reading goals, progress and star ratings.',
  'auth.google': 'Continue with Google',
  'auth.or': 'or with email',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.name': 'Your name',
  'auth.signIn': 'Sign in',
  'auth.register': 'Create account',
  'auth.toSignIn': 'Already a member? Sign in',
  'auth.toRegister': 'New here? Create an account',
  'auth.forgot': 'Forgot password?',
  'auth.resetSent': 'If there’s an account, a reset link is on its way.',
  'auth.needEmail': 'Enter your email address first.',
  'auth.err.credentials': 'Email or password is incorrect.',
  'auth.err.emailInUse': 'There’s already an account for this email — just sign in.',
  'auth.err.weakPassword': 'The password needs at least 6 characters.',
  'auth.err.invalidEmail': 'That doesn’t look like a valid email address.',
  'auth.err.popup': 'The sign-in window was closed or blocked.',
  'auth.err.domain': 'This address isn’t authorised in Firebase yet (Authentication → Settings → Authorized domains).',
  'auth.err.disabled': 'This sign-in method isn’t enabled in Firebase yet (Authentication → Sign-in method).',
  'auth.err.network': 'No connection. Are you online?',
  'auth.err.tooMany': 'Too many attempts — wait a moment and try again.',

  'demo.title': 'Demo mode',
  'demo.intro': 'Firebase isn’t connected yet. You can still try Bookwheel with a sample club — saved only in this browser.',
  'demo.start': 'Start the demo',
  'demo.banner': 'Demo mode · everything stays in this browser',
  'demo.reset': 'Reset demo',
  'demo.setup': 'Setup',

  'club.createTitle': 'Start your book club',
  'club.createIntro': 'There’s no club here yet. You’ll be the founder and get an invite code for everyone else.',
  'club.name': 'Club name',
  'club.namePlaceholder': 'e.g. The Page Turners',
  'club.create': 'Create club',
  'club.joinTitle': 'Join {club}',
  'club.joinIntro': 'Enter the invite code your club shared with you.',
  'club.code': 'Invite code',
  'club.join': 'Join',
  'club.badCode': 'That code doesn’t match. Double-check with your club.',
  'club.signedInAs': 'Signed in as {who}',
  'club.switchAccount': 'Use another account',

  'nav.wheel': 'Wheel',
  'nav.current': 'Reading',
  'nav.shelf': 'Shelf',
  'nav.chronicle': 'Chronicle',
  'menu.profile': 'Profile',
  'menu.club': 'Club & invite',
  'menu.signOut': 'Sign out',
  'menu.language': 'Language',
  'menu.theme': 'Theme',
  'menu.sound': 'Wheel sounds',
  'menu.on': 'on',
  'menu.off': 'off',
  'theme.system': 'Auto',
  'theme.light': 'Light',
  'theme.dark': 'Dark',

  'hero.morning': 'Good morning, {name}',
  'hero.day': 'Hello, {name}',
  'hero.evening': 'Good evening, {name}',
  'hero.title': 'What are we reading next?',
  'hero.titleReading': 'Read together, spin together.',

  'wheel.title': 'The wheel',
  'wheel.count': ({ n }) => plural(n, '{n} book on the wheel', '{n} books on the wheel'),
  'wheel.filter': 'Filter by genre',
  'wheel.allGenres': 'All genres',
  'wheel.spin': 'Spin!',
  'wheel.spinning': 'Spinning…',
  'wheel.empty': 'The shelf is empty — add a few books.',
  'wheel.emptyFilter': 'Nothing on the shelf in these genres right now.',
  'wheel.emptyCenter': 'Fill the shelf',
  'wheel.confirmReplace': 'You’re currently reading “{title}”. Spin for a new book anyway?',
  'wheel.confirmYes': 'Yes, spin',
  'wheel.taken': '“{title}” was just picked already.',

  'result.eyebrow': 'The wheel has spoken',
  'result.byOther': '{name} spun the wheel!',
  'result.month': 'Book for',
  'result.start': 'Let’s read!',
  'result.undo': 'Put it back',
  'result.undone': '“{title}” is back on the shelf.',
  'result.pages': '{n} pages',

  'current.eyebrow': 'Current book',
  'current.none': 'No current book yet',
  'current.noneHint': 'Spin the wheel — the pick lands here and everyone reads along.',
  'current.pickedBy': 'picked by {name}',
  'current.forMonth': 'Book for {month}',
  'current.pages': '{n} pages',
  'current.myProgress': 'My progress',
  'current.page': 'Page',
  'current.ofPages': 'of {n}',
  'current.update': 'Save',
  'current.saved': 'Progress saved — page {page}',
  'current.markRead': 'Mark as read',
  'current.finished': 'Finished',
  'current.rateNow': 'Rate it now',
  'current.editRating': 'Edit rating',
  'current.yourRating': 'Your rating',
  'current.notFinished': 'Not finished after all',
  'current.pageCountMissing': 'How many pages does it have?',
  'current.setPages': 'Apply',

  'goals.title': 'Reading goals',
  'goals.empty': 'No reading goals yet. Decide how far everyone should be by when.',
  'goals.item': 'By {date} · page {page}',
  'goals.add': 'Add goal',
  'goals.date': 'By',
  'goals.page': 'Page',
  'goals.today': 'today',
  'goals.tomorrow': 'tomorrow',
  'goals.inDays': ({ n }) => plural(n, 'in {n} day', 'in {n} days'),
  'goals.past': 'passed',
  'goals.reached': ({ n, m }) => `${n} of ${m} there`,
  'goals.next': 'Next goal',
  'goals.remove': 'Remove goal',
  'goals.added': 'Reading goal saved',
  'goals.invalid': 'Please enter a date and a page.',

  'ticker.title': 'Who’s where?',
  'ticker.page': 'p. {page}',
  'ticker.ofPages': 'p. {page} / {total}',
  'ticker.notStarted': 'not started yet',
  'ticker.finished': 'finished!',
  'ticker.behind': ({ n }) => `${n} pages behind`,
  'ticker.reached': 'goal reached',
  'ticker.toGo': ({ n }) => `${n} pages to the goal`,
  'ticker.empty': 'Once a book is picked, you’ll see how far everyone is right here.',

  'shelf.title': 'The shelf',
  'shelf.sub': 'Everything on here goes onto the wheel.',
  'shelf.add': 'Add a book',
  'shelf.search': 'Search the shelf…',
  'shelf.empty': 'The shelf is still empty. Add the first book!',
  'shelf.noMatch': 'Nothing found.',
  'shelf.addedBy': 'from {name}',
  'shelf.removed': 'Removed “{title}” from the shelf',
  'shelf.added': '“{title}” is on the shelf!',
  'shelf.count': ({ n }) => plural(n, '{n} book', '{n} books'),

  'add.title': 'A new book for the shelf',
  'add.lookup': 'Look up a book',
  'add.lookupPlaceholder': 'Type a title or author…',
  'add.lookupHint': 'We’ll find the cover and page count for you — or fill everything in yourself.',
  'add.searching': 'Searching…',
  'add.noResults': 'No matches — just enter the book yourself.',
  'add.bookTitle': 'Title',
  'add.author': 'Author',
  'add.genre': 'Genre',
  'add.pages': 'Pages',
  'add.cover': 'Book cover',
  'add.coverUrl': 'Paste image URL',
  'add.upload': 'Upload image',
  'add.removeCover': 'Remove cover',
  'add.submit': 'Put it on the shelf',
  'add.needGenre': 'Please choose a genre.',
  'add.needTitle': 'We need a title and an author.',
  'add.coverError': 'That image couldn’t be read.',
  'add.badUrl': 'That isn’t a valid image address (https://…).',
  'add.duplicate': '“{title}” is already on the shelf.',

  'edit.title': 'Edit book',
  'edit.remove': 'Remove from shelf',
  'edit.saved': 'Saved',

  'review.title': 'How did you like “{title}”?',
  'review.congrats': 'You made it! Congrats on finishing.',
  'review.text': 'Your review',
  'review.placeholder': 'What did you love, what not so much?',
  'review.submit': 'Submit rating',
  'review.later': 'Rate later',
  'review.saved': 'Thanks for your rating!',
  'review.needStars': 'Pick 1 to 5 stars.',
  'review.sealed': 'Ratings stay hidden until everyone has voted — then the average is revealed.',
  'review.star': ({ n }) => plural(n, '{n} star', '{n} stars'),

  'chron.title': 'Chronicle',
  'chron.sub': 'Every month, every book — and what you all thought of it.',
  'chron.empty': 'Your picks will show up here, month by month.',
  'chron.current': 'Reading now',
  'chron.avg': 'avg {value} of 5',
  'chron.votes': ({ n, m }) => `${n} of ${m} ratings in`,
  'chron.waitingFor': 'Still waiting for {names}',
  'chron.showReviews': 'Read the reviews',
  'chron.hideReviews': 'Hide reviews',
  'chron.sealed': 'The reviews are revealed once everyone has rated.',
  'chron.noText': 'no words, just stars',
  'chron.rate': 'Finished & rate',
  'chron.editRating': 'Edit my rating',
  'chron.setCurrent': 'Make current book',
  'chron.moveMonth': 'Change month',
  'chron.backToShelf': 'Back to the shelf',
  'chron.finishedCount': ({ n }) => plural(n, '{n} has read it', '{n} have read it'),
  'chron.pickedBy': 'picked by {name}',

  'clubm.title': 'Club & invite',
  'clubm.invite': 'Invite code',
  'clubm.inviteHint': 'Send new members the link — or the code, which they enter after signing in.',
  'clubm.copyCode': 'Copy code',
  'clubm.copyLink': 'Copy link',
  'clubm.copied': 'Copied!',
  'clubm.newCode': 'Generate new code',
  'clubm.newCodeDone': 'The new code is live. The old one no longer works.',
  'clubm.members': 'Members',
  'clubm.founder': 'Founder',
  'clubm.remove': 'Remove',
  'clubm.removeConfirm': 'Really remove {name} from the club?',
  'clubm.leave': 'Leave club',
  'clubm.leaveConfirm': 'Do you really want to leave the club?',
  'clubm.rename': 'Rename club',

  'profile.title': 'Your profile',
  'profile.name': 'Display name',
  'profile.color': 'Your colour',
  'profile.saved': 'Profile saved',
};
